apiVersion: v1
kind: Secret
metadata:
  name: openmu-admin
  namespace: openmu-lab
  labels:
    app.kubernetes.io/name: openmu
    app.kubernetes.io/component: openmu
    openmu.saas/server-name: Lab
type: Opaque
stringData:
  OPENMU_ADMIN_USER: admin
  OPENMU_ADMIN_PASSWORD: openmu
  OPENMU_ADMIN_TOTP_SECRET: ""
