apiVersion: v1
kind: Service
metadata:
  name: openmu-postgres
  namespace: openmu-lab
  labels:
    app.kubernetes.io/name: openmu
    app.kubernetes.io/component: postgres
    openmu.saas/server-name: Lab
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: openmu
    app.kubernetes.io/component: postgres
