apiVersion: v1
kind: Secret
metadata:
  name: openmu-postgres
  namespace: openmu-lab
  labels:
    app.kubernetes.io/name: openmu
    app.kubernetes.io/component: postgres
    openmu.saas/server-name: Lab
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: openmu
  DB_ADMIN_USER: postgres
  DB_ADMIN_PW: admin
