apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmu.adminSecretName" . }}
  labels:
    {{- include "openmu.labels" . | nindent 4 }}
    app.kubernetes.io/component: openmu
type: Opaque
stringData:
  OPENMU_ADMIN_USER: {{ .Values.admin.username | quote }}
  OPENMU_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  OPENMU_ADMIN_TOTP_SECRET: {{ .Values.admin.totpSecret | quote }}
