apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmu.postgresName" . }}
  labels:
    {{- include "openmu.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "openmu.postgresSelectorLabels" . | nindent 4 }}
